Upload student data
Bpitorg/bpit_admin_panel pull request #12
Opened 2023-03-07 07:53 UTC by srivastavaritik

2023-03-07 07:56 UTC, jindal2209 commented on src/schemas/schemas.js
> +import * as Yup from "yup";
rename file to signup schemas
it will be better to keep schemas in the individual files

2023-03-07 07:57 UTC, jindal2209 commented on src/components/home/home.js
> +  // React.useEffect(() => {
merge master latest pull

2023-03-07 09:14 UTC, srivastavaritik commented on src/schemas/schemas.js
> +import * as Yup from "yup";
done

2023-03-07 09:14 UTC, srivastavaritik commented on src/components/home/home.js
> +  // React.useEffect(() => {
done

2023-03-07 18:39 UTC, jindal2209 commented on src/components/BulkUploadNote/BulkUploadNote.js
> +import React from "react";
this folder should be inside /components/student
else make it a generic function so that it can be used with other file upload forms

2023-03-07 18:51 UTC, jindal2209 commented
take latest pull of you branch i have made one commit

2023-03-07 18:53 UTC, jindal2209 commented on src/schemas/addStudentSchema.js
> +  enrollment_number: Yup.number().min(11).required("Please enter the Enrollment Number!"),
```suggestion
  enrollment_number: Yup.number().min(11).max(11).required("Please enter the Enrollment Number!"),
```

2023-03-07 18:54 UTC, jindal2209 commented on src/schemas/addStudentSchema.js
> +  enrollment_number: Yup.number().min(11).required("Please enter the Enrollment Number!"),
enrollment number is fixed of length 11

2023-03-07 18:55 UTC, jindal2209 commented on src/schemas/addStudentSchema.js
> +  name: Yup.string().min(2).max(25).required("Please enter the Name!"),
```suggestion
  name: Yup.string().min(3).required("Please enter the Name!"),
```

2023-03-07 19:17 UTC, jindal2209 requested changes
I have suggessted some changes pls check

2023-03-07 19:17 UTC, jindal2209 commented on src/schemas/addStudentSchema.js
> +  class_roll_number: Yup.string().min(3).required("Please enter the Class Roll Number!"),
make this integer with no length constraint

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/student.js
> +          <TabPanel value='1'><AddStudent /></TabPanel>
```suggestion
          <TabPanel value='1'><AddStudent setLoader={setLoader} /></TabPanel>

```

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +const AddStudent = () => {
```suggestion
const AddStudent = ({ setLoader }) => {
```

pls make sure to show loader if making any api call

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +    e.preventDefault();
```suggestion
    setLoader(true)
    e.preventDefault();
```

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +        navigate("/home/students");
```suggestion
        setLoader(true)
        navigate("/home/students");
```

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +        console.log(err.response.data);
```suggestion
        setLoader(false)
        console.log(err.response.data);
```

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +    http_lib
same here
        setLoader(true) to show loader
        setLoader(false) to hide loader

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +      .get(BRANCH_URL)
add loader

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +    console.log(filesToUpload);
remove

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +            <MenuItem value={"2020"}>2020</MenuItem>
make this dynamic use range [currentYear - 5, currentYear + 5]

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +        OR, UPLOAD FILES
"or" should be bigger in size
```suggestion
        <h3>OR </h3> <br /> UPLOAD FILE
```

2023-03-07 19:17 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +      <div
remove react-mui-file-upload if or if not using

2023-03-07 19:41 UTC, jindal2209 commented on src/constants/apiEndpoints.js
> +export const ADD_STUDENT_URL = "/student/profile/add";
```suggestion
export const ADD_STUDENT_URL = "/student/profile/add/";
```

2023-03-07 19:43 UTC, jindal2209 commented on src/components/home/student/AddStudent.js
> +  function handleSubmit(e) {
pls check the endpoint on postman again
you missed "is_file" field

2023-03-12 08:03 UTC, jindal2209 approved these changes

2023-03-12 08:04 UTC, merged